import './globals.css'
import {Poppins} from 'next/font/google'
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";

const poppins = Poppins({subsets: ["latin"], weight: ["400", "500", "600", "700", "800", "900"]})

export const metadata = {
    title: 'Blog App',
    description: 'Generated by Nikhil Ganireddy',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={poppins.className}>
        <div className="container mx-auto min-h-screen max-w-[1600px] w-full flex flex-col space-y-6">
            <Navbar/>
            {children}
            <Footer/>
        </div>
        </body>
        </html>
    )
}
